spring:
  application:
    name: springbootWithZk
  threads:
    virtual:
       enabled: true
#it will overwrite lockback-spring.xml
logging:
  level: 
    org:
      springframework:
        web: DEBUG
        servlet:
          resource: TRACE